# Generated by Django 3.1.3 on 2021-04-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_auto_20210331_1736'),
        ('Producto', '0063_auto_20210330_0900'),
        ('Store', '0002_auto_20210325_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('por_confirmar', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.usuariosweb')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompraWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_normal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio_promocion', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.comprasweb')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.productos')),
            ],
        ),
    ]
