# Generated by Django 3.1.3 on 2021-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_comprasweb_detallecompraweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasweb',
            name='hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
