# Generated by Django 3.1.3 on 2021-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210403_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasweb',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
