# Generated by Django 3.1.3 on 2021-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_detallecompraweb_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompraweb',
            name='talla',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
