# Generated by Django 3.1.3 on 2021-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_detallecompraweb_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompraweb',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
