# Generated by Django 3.1.3 on 2021-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_detallecompraweb_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompraweb',
            name='enviado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
