# Generated by Django 3.1.3 on 2021-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompraweb',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detallecompraweb',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
