# Generated by Django 3.1.3 on 2020-11-25 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_categorias_colores_detallesproducto_imagenesproducto_kardex_precios_productos_subcategorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesproducto',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='detallesproducto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detallesproducto',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='detallesproducto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='detallesproducto',
            name='iva',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detallesproducto',
            name='pc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detallesproducto',
            name='precioCompra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detallesproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.productos'),
        ),
    ]
