# Generated by Django 3.1.3 on 2020-11-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_auto_20201124_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesproducto',
            options={'verbose_name_plural': '4. Detalles del Producto '},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': '3. Producto '},
        ),
        migrations.RenameField(
            model_name='colores',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='kardex',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='precios',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='subcategoria_id',
            new_name='subcategoria',
        ),
    ]
