# Generated by Django 3.1.3 on 2020-11-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_auto_20201124_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precios',
            options={'verbose_name_plural': '6. Precios Producto '},
        ),
    ]
