# Generated by Django 3.1.3 on 2020-11-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_auto_20201125_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenesproducto',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombreComercial',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='subcategorias',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, help_text='100x100', null=True, upload_to='proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_actividad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.IntegerField(max_length=13),
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, choices=[('productos/bienes', 'productos/bienes'), ('servicios', 'servicios'), ('recursos', 'recursos')], max_length=30, null=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.TextField(max_length=200)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.proveedor')),
            ],
        ),
    ]
