# Generated by Django 3.1.3 on 2020-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_auto_20201126_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.CharField(default='fa fa-', max_length=20),
        ),
    ]
