# Generated by Django 3.1.3 on 2020-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0011_auto_20201126_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=13),
        ),
    ]
