# Generated by Django 3.1.3 on 2020-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_auto_20201126_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='icono',
            field=models.CharField(max_length=20),
        ),
    ]
