# Generated by Django 3.1.3 on 2020-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0015_auto_20201126_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='dimension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
