# Generated by Django 3.1.3 on 2020-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0016_auto_20201126_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='dimension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
