# Generated by Django 3.1.3 on 2020-11-26 15:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0017_auto_20201126_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100),
        ),
    ]
