# Generated by Django 3.1.3 on 2020-11-26 15:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0019_auto_20201126_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='detallesTecnicos',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Es opcional', null=True),
        ),
    ]
