# Generated by Django 3.1.3 on 2020-11-26 15:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0020_auto_20201126_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colores',
            name='codigoColor',
            field=colorfield.fields.ColorField(default='#fff', max_length=18),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='iva',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Calculado automaticamente', max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallesproducto',
            name='pc',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Calculado automaticamente', max_digits=9),
        ),
    ]
