# Generated by Django 3.1.3 on 2020-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0022_auto_20201126_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadproveedor',
            name='detalle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='detalle',
            field=models.TextField(),
        ),
    ]
