# Generated by Django 3.1.3 on 2020-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0023_auto_20201126_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(blank=True, choices=[('productos/bienes', 'productos/bienes'), ('servicios', 'servicios'), ('recursos', 'recursos')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
