# Generated by Django 3.1.3 on 2020-11-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0024_auto_20201126_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_actividad',
        ),
    ]
