# Generated by Django 3.1.3 on 2020-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0026_remove_proveedor_tipo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionproveedor',
            name='telefono',
            field=models.CharField(max_length=60),
        ),
    ]
