# Generated by Django 3.1.3 on 2020-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0028_auto_20201130_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
