# Generated by Django 3.1.3 on 2020-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0029_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, help_text='Solo si tiene codigo interno o codigo de barras', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagen de 100px x 100px', null=True, upload_to='productos'),
        ),
    ]
