# Generated by Django 3.1.3 on 2020-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0030_auto_20201222_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
