# Generated by Django 3.1.3 on 2020-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0031_auto_20201229_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
