# Generated by Django 3.1.3 on 2020-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0033_auto_20201229_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='tipo',
            field=models.CharField(max_length=1),
        ),
    ]
