# Generated by Django 3.1.3 on 2020-12-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0034_auto_20201230_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
