# Generated by Django 3.1.3 on 2021-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0035_precios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='precios',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
