# Generated by Django 3.1.3 on 2021-02-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0037_auto_20210128_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
