# Generated by Django 3.1.3 on 2021-02-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0039_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
