# Generated by Django 3.1.3 on 2021-02-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0040_promociones_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promociones',
            name='precio',
        ),
        migrations.AddField(
            model_name='promociones',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.productos'),
        ),
    ]
