# Generated by Django 3.1.3 on 2021-02-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0041_auto_20210223_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promociones',
        ),
    ]
