# Generated by Django 3.1.3 on 2021-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0042_delete_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
