# Generated by Django 3.1.3 on 2021-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0044_auto_20210323_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionproductos',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
