# Generated by Django 3.1.3 on 2021-03-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0048_auto_20210323_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
