# Generated by Django 3.1.3 on 2021-03-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [
        ('Producto', '0051_auto_20210325_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionproductos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.productos', unique=True),
        ),
    ]
