# Generated by Django 3.1.3 on 2021-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0056_imagenesproducto_thumbails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesproducto',
            name='thumbails',
        ),
    ]
