# Generated by Django 3.1.3 on 2021-03-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0058_imagenesproducto_thumbails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenesproducto',
            old_name='thumbails',
            new_name='thumbnail',
        ),
    ]
