# Generated by Django 3.1.3 on 2021-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0059_auto_20210325_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='producto/thumbnail'),
        ),
    ]
