# Generated by Django 3.1.3 on 2021-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0060_auto_20210325_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='600x800', null=True, upload_to='producto'),
        ),
    ]
