# Generated by Django 3.1.3 on 2021-04-09 00:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0063_auto_20210330_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='detallesTecnicos',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Sin detalles Técnicos', help_text='Es opcional', null=True),
        ),
    ]
