# Generated by Django 3.1.3 on 2021-04-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0067_auto_20210408_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='subcategorias',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='subcategorias',
            name='icono',
        ),
        migrations.CreateModel(
            name='Subcategorias_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.subcategorias')),
            ],
            options={
                'verbose_name_plural': '2. Subcategorias ',
            },
        ),
    ]
