# Generated by Django 3.1.3 on 2021-04-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0068_auto_20210408_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorias_2',
            options={'verbose_name_plural': '2.1 Subcategorias Subcategoría'},
        ),
    ]
