# Generated by Django 3.1.3 on 2021-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0069_auto_20210408_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
