# Generated by Django 3.1.3 on 2021-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0071_auto_20210408_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='etiquetas',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
