# Generated by Django 3.1.3 on 2021-04-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0073_auto_20210409_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='establecimiento',
        ),
    ]
