# Generated by Django 3.1.3 on 2021-01-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_facturas_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
