# Generated by Django 3.1.3 on 2021-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_facturas_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precioU',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
