# Generated by Django 3.1.3 on 2021-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_detallefactura_preciou'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
