# Generated by Django 3.1.3 on 2021-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_detallefactura_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='estado',
            field=models.CharField(default='E', max_length=1),
        ),
    ]
