# Generated by Django 3.1.3 on 2021-02-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_clientes_estado'),
        ('Ventas', '0006_facturas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('factura_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('formaPago', models.CharField(max_length=20)),
                ('numeroCheque', models.CharField(blank=True, max_length=20, null=True)),
                ('rebidoPor', models.CharField(max_length=60)),
                ('recibiDe', models.CharField(max_length=60)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.cuentascobrar')),
            ],
        ),
    ]
