# Generated by Django 3.1.3 on 2020-11-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='direccion',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.tienda'),
        ),
    ]
