# Generated by Django 3.1.3 on 2020-11-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201117_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.tienda'),
        ),
    ]
