# Generated by Django 3.1.3 on 2020-11-17 17:07

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20201117_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='Home.usuario'),
        ),
    ]
