# Generated by Django 3.1.3 on 2020-11-17 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20201117_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
