# Generated by Django 3.1.3 on 2020-11-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_direccion_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
