# Generated by Django 3.1.3 on 2020-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20201124_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombreComercial',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
