# Generated by Django 3.1.3 on 2020-11-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20201124_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
