# Generated by Django 3.1.3 on 2021-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_configurardocumentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurardocumentos',
            name='facturas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configurardocumentos',
            name='proformas',
            field=models.IntegerField(default=1),
        ),
    ]
