# Generated by Django 3.1.3 on 2021-03-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20210127_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurarDocumentos',
        ),
    ]
