# Generated by Django 3.1.3 on 2020-11-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20201124_0951'),
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.usuario'),
        ),
    ]
