# Generated by Django 3.1.3 on 2020-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_auto_20201124_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=60)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
