# Generated by Django 3.1.3 on 2020-11-24 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Empresa', '0005_auto_20201124_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='UsuarioEmpresa',
        ),
    ]
