# Generated by Django 3.1.3 on 2020-11-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0006_auto_20201124_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/establecimientos'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/establecimientos'),
        ),
    ]
