# Generated by Django 3.1.3 on 2021-01-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0007_auto_20201125_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='pie_pagina',
            field=models.ImageField(blank=True, null=True, upload_to='pie/establecimientos'),
        ),
    ]
