# Generated by Django 3.1.3 on 2021-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0008_establecimiento_pie_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='facebook',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='instagram',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='ubicacion_gps',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='web',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='youtube',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
