# Generated by Django 3.1.3 on 2021-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0011_configurardocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='color_encabezado_documentos',
            field=models.CharField(default='#ffffff', max_length=40),
        ),
    ]
