# Generated by Django 3.1.3 on 2021-04-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0013_auto_20210410_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='facebook',
            field=models.CharField(blank=True, default=' ', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='instagram',
            field=models.CharField(blank=True, default=' ', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='youtube',
            field=models.CharField(blank=True, default=' ', max_length=400, null=True),
        ),
    ]
