# Generated by Django 3.1.3 on 2021-04-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0014_auto_20210410_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='banner1',
            field=models.ImageField(blank=True, null=True, upload_to='logos/tienda'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='logos/tienda'),
        ),
    ]
