# Generated by Django 3.1.3 on 2021-03-30 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0014_delete_configurardocumentos'),
        ('Personas', '0004_clientes_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionesWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('envio', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
                ('facturacion', models.BooleanField(default=False)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ciudad')),
                ('usuarioWeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.usuariosweb')),
            ],
        ),
    ]
