# Generated by Django 3.1.3 on 2021-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0005_direccionesweb_usuariosweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionesweb',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
