# Generated by Django 3.1.3 on 2021-03-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_direccionesweb_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosweb',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuariosweb',
            name='nombres',
        ),
    ]
