# Generated by Django 3.1.3 on 2021-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_auto_20210410_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
